### ISSUE TITLE
꼬들 개발자입니다.

### ISSUE THREAD

**Issue by belorin** [Jep4/Kordle-CheatKey#1]
들녘까지 포함되어 있는 것을 보면 최신 단어 데이터인데, 이 데이터를 어디서 추출하셨을까요?

**Comment by Jep4** [comment]
안녕하세요! 크롬 개발자 도구 (js>constants)에 나와있어 그 데이터를 가져왔습니다
바로 나와있길래 사용해도 되는 데이터라고 생각했는데, 혹시 아니었다면 내리도록 하겠습니다 ㅠㅠ
ᐧ

**Comment by belorin** [comment]
그렇게 바로 노출이 되어 있었군요. 몰랐습니다. 많은 분들이 미리 알게 될 경우 모두가 즐겁게 즐기지 못하게 될 것 같아서 슬픕니다. 개인적으로 사용하시면 좋겠습니다. 보안상의 문제점을 알게 해주셔서 감사합니다.

**Comment by Jep4** [comment]
짧은 생각으로 일을 진행해 심려 끼쳐드린 점 정말 죄송합니다.
곤란하셨을 텐데 좋게 말씀 주셔서 감사드려요. 데이터가 포함된 파일은 전부 삭제했습니다!
좋은 밤 보내시길 바라겠습니다.
ᐧ

**Comment by belorin** [comment]
아닙니다. 열심히 개발 하셨을 텐데 이런 말씀 드려서 죄송합니다. 밤늦게 질문 드렸는데 이렇게까지 빨리 답변 주실 줄은 몰랐습니다.
요청대로 해주셔서 정말 감사합니다. Jep4님도 좋은 불금 보내시기 바랍니다.
